networks:
  project:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}

volumes:
  db:
    name: ${COMPOSE_PROJECT_NAME}_db_data
  app-home:
    name: ${COMPOSE_PROJECT_NAME}_app_home_dir

services:
  app:
    build:
      context: .docker
      dockerfile: dev.Dockerfile
      args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - USER_SHELL=${USER_SHELL}
        - USER_TERM=${TERM:-xterm-256color}
        - ZSHTHEME=${ZSH_THEME:-maran}
        - PROJECT_PATH=/project
    volumes:
      - type: volume
        source: app-home
        target: /home/app
        volume:
          nocopy: false
      - .:/project
    env_file:
      - .docker/.env
    networks:
      - project
    ports:
      - '8000:8000'
    command: /home/app/.local/bin/poetry run python manage.py runserver 0.0.0.0:8000
    user: app
    depends_on:
      - db
  
  db:
    image: postgres:16
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .docker/.env
    networks:
      - project
    ports:
      - '5432:5432'
